# Generated by Django 5.1.6 on 2025-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab', '0002_user_description_user_image_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='bannerPicture',
            field=models.ImageField(default='images/banner.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='images/Sigil3.png', upload_to='images/'),
        ),
    ]
